spring.application.name=postgres-connector

server.port=8088
spring.datasource.url=jdbc:mysql://localhost:3306/ram
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#spring.datasource.url=jdbc:postgresql://localhost:5432/anand
#spring.datasource.username=postgres
#spring.datasource.password=Anand@123
#server.port=8888
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

